### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by iProgYou** [lijasontse/Mealtime#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- I think birthday is unnecessary. If you did end up using it I think it would be a date data type rather than an int.
- I think you may want a foreign key in your businesses table to reference the user that created the business page
- Looks great overall

**Comment by lijasontse** [comment]
Thanks for the review Zack, I have gone ahead and removed birthday from the user's table as well as added an owner_id as a foreign_key to the businesses table.

**Comment by iProgYou** [comment]
Eventually you may want a joins table for category. Not sure. We will talk about it in the 1 on 1.
