### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by iProgYou** [lijasontse/Mealtime#4]
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments
- What will they see after login? Splash? Business Index?

**Comment by lijasontse** [comment]
Hey Zack, I updated the login portion of my front end routes, after the user logins, they will be redirected to the home page, where they can search for a business.
